### ISSUE TITLE
Feature not working.

### ISSUE THREAD

**Issue by Psoz** [wmcmurray/just-detect-adblock#3]
I believe that this feature stop working.
I'm trying to figure out, and maybe help with a Merge request.

Any help you can give, is a plus.

Thanks

**Comment by guanzo** [comment]
Stopped working for me too, but I can't remember exactly when. Probably around chrome 85/86?

**Comment by wmcmurray** [comment]
Thanks for your investigation @guanzo !

I implemented your findings in [this commit](https://github.com/wmcmurray/just-detect-adblock/commit/f6a91cf0c4b10e1559073945a6ba30f0fee37829), it should be fixed and available in the latest release `v1.1.0` !
( if I did not mess up something 🤞🏻 I haven't played with npm packages for years 😬 ! )
